theme: jekyll-theme-leap-day
title: "Team 10"
description: "Blog for the Team 10 coding group in APCSA and home of future website!"
gitorg: "https://github.com/guapbeast/team10"
description: "June 26 to July 1 2023"
google_analytics:
