theme: jekyll-theme-bulma
title: "Team 10"
description: "Blog for the Team 10 coding group in APCSA and home of future website!"
gitorg: "https://github.com/guapbeast/team10"
description: "November to March"
google_analytics:
